char *help_msg = "Usage: passman [COMMAND] or passman passman> [COMMAND]\n"
"\n"
"COMMAND:\n"
"	help - display this message\n"
"	quit - exit the program \n"
"	search <username> - find the corresponding password in the database for the <username>\n"
"	delete <username> - removes every occurance of the username in the database \n"
"	add <username> <password> - inserts the username and password into the database\n"
"\n"
"";
